imports:
    - { resource: parameters.yml }

services:
    davidiq.multitopicicons.service:
        class: davidiq\multitopicicons\service
        arguments:
            - '@cache'
            - '@config'
            - '@template'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%davidiq.multitopicicons.tables.topic_icons%'

    davidiq.multitopicicons.listener:
        class: davidiq\multitopicicons\event\main_listener
        arguments:
            - '@language'
            - '@template'
            - '@request'
            - '@davidiq.multitopicicons.service'
            - '%davidiq.multitopicicons.tables.topic_icons%'
        tags:
            - { name: event.listener }
