services:
    davidiq.multitopicicons.service:
        class: davidiq\multitopicicons\service
        arguments:
            - '@cache'
            - '@config'
            - '@template'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.table_prefix%topic_icons'

    davidiq.multitopicicons.listener:
        class: davidiq\multitopicicons\event\main_listener
        arguments:
            - '@language'
            - '@template'
            - '@request'
            - '@davidiq.multitopicicons.service'
        tags:
            - { name: event.listener }
